### ISSUE TITLE
poilo plugin bug

### ISSUE THREAD

**Issue by Nephos** [pouleta/botpop#20]
``` text

[2015/08/24 16:22:56.454] >> :poulet_a!~poulet_a@unaffiliated/poulet-a/x-4015932 PRIVMSG #equilibre :whoooooooooooooooooooooooot
[2015/08/24 16:22:56.455] !! [New thread] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x00561802c73e70 @prefix=nil, @pattern=/^[^!].*/, @suffix=nil>>: #<Thread:0x005618036e6498> -- 1 in total.
[2015/08/24 16:22:56.456] !! [New thread] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x00561802c72138 @prefix=nil, @pattern=/^[^!].*/, @suffix=nil>>: #<Thread:0x005618036e57c8> -- 1 in total.
[2015/08/24 16:22:56.457] !! [New thread] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x00561802dd2e60 @prefix=nil, @pattern=/^[^!].+/, @suffix=nil>>: #<Thread:0x005618036cf0e0> -- 1 in total.
[2015/08/24 16:22:56.457] !! [New thread] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x00561802d72b78 @prefix=nil, @pattern=/.+/, @suffix=nil>>: #<Thread:0x005618036e4a58> -- 1 in total.
[2015/08/24 16:22:56.457] !! /home/poulet_a/Projects/botpop/plugins/poilo.rb:15:in `+': no implicit conversion of nil into String (TypeError)
[2015/08/24 16:22:56.458] !!    /home/poulet_a/Projects/botpop/plugins/poilo.rb:15:in `exec_poilo'
[2015/08/24 16:22:56.458] !!    /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cinch-2.2.6/lib/cinch/plugin.rb:419:in `call'
[2015/08/24 16:22:56.458] !!    /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cinch-2.2.6/lib/cinch/plugin.rb:419:in `block (2 levels) in __register_matchers'
[2015/08/24 16:22:56.458] !!    /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cinch-2.2.6/lib/cinch/handler.rb:99:in `call'
[2015/08/24 16:22:56.458] !!    /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cinch-2.2.6/lib/cinch/handler.rb:99:in `block in call'

```

**Comment by Nephos** [comment]
```
plugins/poilo.rb:15:in `+': no implicit conversion of nil into String (TypeError)
```
